###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "2"
services:

    memcached:
      image: memcached:alpine
      container_name: phpobjects-memcached

    redis:
      image: redis:alpine
      container_name: phpobjects-redis

    mysql:
      image: mysql:8.0
      container_name: phpobjects-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root123
        - MYSQL_DATABASE=phpObjects
        - MYSQL_USER=alex
        - MYSQL_PASSWORD=alex123
      ports:
        - "1266:3306"

    postgres:
      image: postgres:9.6-alpine
      container_name: phpobjects-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root123
        - POSTGRES_DB=phpObjects

    webserver:
      image: nginx:alpine
      container_name: phpobjects-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "1264:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: phpobjects-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

